export const LOGINING = "LOGINING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const GET_TOKEN = "GET_TOKEN"

export const GETTING_DEVICES = "GETTING_DEVICES"
export const GET_SUCCESS_DEVICES = "GET_SUCCESS_DEVICES"
export const GET_FAIL_DEVICES = "GET_FAIL_DEVICES"

export const DELETED_DEVICE = "DELETED_DEVICE"

export const ADDING_DEVICE = "ADDING_DEVICE"
export const ADDED_DEVICE = "ADDED_DEVICE"
export const ADD_FAIL_DEVICE = "ADD_FAIL_DEVICE"